// This build script is a very lazy translation of `gettzmapping.php` from
// timelib <https://github.com/derickr/timelib>, modified so the resulting
// table can be searched with binary search instead of requiring a linear scan.
//
// The upstream copyright is:
//
// SPDX-License-Identifier: MIT
// SPDX-Copyright-Text: Copyright (c) 2015-2023 Derick Rethans
// SPDX-Copyright-Text: Copyright (c) 2018 MongoDB, Inc.

use regex::Regex;
use std::{
    collections::{BTreeMap, BTreeSet, HashMap, HashSet},
    env,
    fs::File,
    io::{BufWriter, Write},
    path::Path,
    sync::LazyLock,
};

fn build_tz_list(out: &mut impl Write) {
    let accepted_tz_name =
        Regex::new("^(?:(?:[A-Z][a-z]+(?:[_/-][A-Za-z]+)+)|[A-Z]{1,6})$").unwrap();
    let rejected_abbr_name = Regex::new("^(?:[+-](?:[0-9]{2}|[0-9]{4})|LMT)$").unwrap();

    let priority_a = &PRIORITY_A_LIST;
    let priority_b = &PRIORITY_B_LIST;

    let mut mapping = BTreeMap::new();

    for name in tzdb_data::TZ_NAMES
        .iter()
        .filter(|name| accepted_tz_name.is_match(name))
    {
        let zone = tzdb_data::find_tz(name.as_bytes()).unwrap();
        for local in zone.local_time_types() {
            if rejected_abbr_name.is_match(local.time_zone_designation()) {
                continue;
            }
            let key = (
                local.time_zone_designation().to_string(),
                local.ut_offset(),
                local.is_dst(),
            );
            let zone_map = mapping.entry(key).or_insert(vec![]);
            if !zone_map.contains(name) {
                zone_map.push(*name);
            }
        }
    }

    for (index, name) in ('a'..='i').chain('k'..='m').enumerate() {
        mapping.insert((name.into(), 3600 * (index as i32 + 1), false), vec![""]);
    }
    for (index, name) in ('n'..='y').enumerate() {
        mapping.insert((name.into(), -3600 * (index as i32 + 1), false), vec![""]);
    }
    mapping.insert(("z".into(), 0, false), vec![""]);
    mapping.insert(("cast".into(), 34200, false), vec!["Australia/Adelaide"]);
    mapping.insert(("utc".into(), 0, false), vec!["UTC"]);

    let mut mapping2 = BTreeSet::new();
    for ((abbr, offset, is_dst), test) in mapping {
        let abbr = abbr.to_ascii_lowercase();

        let ignore_name = if let Some(&(b_dst, b_offset, b_name)) = priority_b.get(abbr.as_str())
            && offset == b_offset
            && is_dst == b_dst
        {
            let priority = if let Some(other) = priority_a.get(abbr.as_str())
                && *other == b_name
            {
                0
            } else {
                1
            };

            let value = (abbr.clone(), priority, offset, is_dst);
            if !mapping2.contains(&value) {
                mapping2.insert(value);
            }

            Some(b_name)
        } else {
            None
        };

        for name in test {
            if Some(name) == ignore_name {
                continue;
            }

            let priority = if let Some(other) = priority_a.get(abbr.as_str())
                && *other == name
            {
                1
            } else {
                2
            };

            let value = (abbr.clone(), priority, offset, is_dst);
            if !mapping2.contains(&value) {
                mapping2.insert(value);
            }
        }
    }

    let mut emitted = HashSet::new();
    for (abbr, _, offset, is_dst) in mapping2 {
        let abbr = abbr.to_ascii_uppercase();
        if emitted.contains(&abbr) {
            continue;
        }
        writeln!(
            out,
            "    TzMapping {{ abbr: {abbr:?}, is_dst: {is_dst:?}, offset: {offset:?} }},"
        )
        .unwrap();
        emitted.insert(abbr);
    }
}

fn main() {
    let path = Path::new(&env::var("OUT_DIR").unwrap()).join("timelib_timezonemap.rs");
    let mut file = BufWriter::new(File::create(&path).unwrap());

    println!("cargo::rerun-if-changed=build.rs");

    writeln!(&mut file, "&[").unwrap();
    build_tz_list(&mut file);
    writeln!(&mut file, "]").unwrap();
}

static PRIORITY_A_LIST: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {
    HashMap::from([
        ("acst", "America/Porto_Acre"),
        ("act", "America/Porto_Acre"),
        ("acdt", "Australia/Adelaide"),
        ("acst", "Australia/Adelaide"),
        ("addt", "America/Goose_Bay"),
        ("adt", "America/Halifax"),
        ("aedt", "Australia/Melbourne"),
        ("aest", "Australia/Melbourne"),
        ("aft", "Asia/Kabul"),
        ("ahdt", "America/Anchorage"),
        ("ahst", "America/Anchorage"),
        ("akdt", "America/Anchorage"),
        ("akst", "America/Anchorage"),
        ("aktst", "Asia/Aqtobe"),
        ("aktt", "Asia/Aqtobe"),
        ("almst", "Asia/Almaty"),
        ("almt", "Asia/Almaty"),
        ("amst", "Asia/Yerevan"),
        ("amt", "Asia/Yerevan"),
        ("anast", "Asia/Anadyr"),
        ("anat", "Asia/Anadyr"),
        ("ant", "America/Curacao"),
        ("apt", "America/Halifax"),
        ("aqtst", "Asia/Aqtau"),
        ("aqtt", "Asia/Aqtau"),
        ("arst", "America/Buenos_Aires"),
        ("art", "America/Buenos_Aires"),
        ("ashst", "Asia/Ashkhabad"),
        ("asht", "Asia/Ashkhabad"),
        ("ast", "Asia/Riyadh"),
        ("awt", "America/Halifax"),
        ("awdt", "Australia/Perth"),
        ("awst", "Australia/Perth"),
        ("azomt", "Atlantic/Azores"),
        ("azost", "Atlantic/Azores"),
        ("azot", "Atlantic/Azores"),
        ("azst", "Asia/Baku"),
        ("azt", "Asia/Baku"),
        ("bakst", "Asia/Baku"),
        ("bakt", "Asia/Baku"),
        ("bdst", "Europe/London"),
        ("bdt", "America/Adak"),
        ("beat", "Africa/Mogadishu"),
        ("beaut", "Africa/Nairobi"),
        ("bmt", "America/Barbados"),
        ("bnt", "Asia/Brunei"),
        ("bortst", "Asia/Kuching"),
        ("bort", "Asia/Kuching"),
        ("bost", "America/La_Paz"),
        ("bot", "America/La_Paz"),
        ("brst", "America/Sao_Paulo"),
        ("brt", "America/Sao_Paulo"),
        ("bst", "Europe/London"),
        ("btt", "Asia/Thimbu"),
        ("burt", "Asia/Kolkata"),
        ("cadt", "Australia/Adelaide"),
        ("cant", "Atlantic/Canary"),
        ("cast", "Australia/Adelaide"),
        ("cat", "America/Anchorage"),
        ("cawt", "America/Anchorage"),
        ("cddt", "America/Rankin_Inlet"),
        ("cdt", "America/Chicago"),
        ("cemt", "Europe/Berlin"),
        ("cest", "Europe/Berlin"),
        ("cet", "Europe/Berlin"),
        ("cgst", "America/Scoresbysund"),
        ("cgt", "America/Scoresbysund"),
        ("chadt", "Pacific/Chatham"),
        ("chast", "Pacific/Chatham"),
        ("chat", "Asia/Harbin"),
        ("chdt", "America/Belize"),
        ("chost", "Asia/Choibalsan"),
        ("chot", "Asia/Choibalsan"),
        ("cit", "Asia/Dili"),
        ("cjt", "Asia/Sakhalin"),
        ("ckhst", "Pacific/Rarotonga"),
        ("ckt", "Pacific/Rarotonga"),
        ("clst", "America/Santiago"),
        ("clt", "America/Santiago"),
        ("cost", "America/Bogota"),
        ("cot", "America/Bogota"),
        ("cpt", "America/Chicago"),
        ("cst", "America/Chicago"),
        ("cvst", "Atlantic/Cape_Verde"),
        ("cvt", "Atlantic/Cape_Verde"),
        ("cwt", "America/Chicago"),
        ("chst", "Pacific/Guam"),
        ("dact", "Asia/Dacca"),
        ("davt", "Antarctica/Davis"),
        ("ddut", "Antarctica/DumontDUrville"),
        ("dusst", "Asia/Dushanbe"),
        ("dust", "Asia/Dushanbe"),
        ("easst", "Chile/EasterIsland"),
        ("east", "Chile/EasterIsland"),
        ("eat", "Africa/Khartoum"),
        ("ect", "America/Guayaquil"),
        ("eddt", "America/Iqaluit"),
        ("edt", "America/New_York"),
        ("eest", "Europe/Helsinki"),
        ("eet", "Europe/Helsinki"),
        ("egst", "America/Scoresbysund"),
        ("egt", "America/Scoresbysund"),
        ("ehdt", "America/Santo_Domingo"),
        ("eit", "Asia/Jayapura"),
        ("ept", "America/New_York"),
        ("est", "America/New_York"),
        ("ewt", "America/New_York"),
        ("fjst", "Pacific/Fiji"),
        ("fjt", "Pacific/Fiji"),
        ("fkst", "Atlantic/Stanley"),
        ("fkt", "Atlantic/Stanley"),
        ("fnst", "America/Noronha"),
        ("fnt", "America/Noronha"),
        ("fort", "Asia/Aqtau"),
        ("frust", "Asia/Bishkek"),
        ("frut", "Asia/Bishkek"),
        ("galt", "Pacific/Galapagos"),
        ("gamt", "Pacific/Gambier"),
        ("gbgt", "America/Guyana"),
        ("gest", "Asia/Tbilisi"),
        ("get", "Asia/Tbilisi"),
        ("gft", "America/Cayenne"),
        ("ghst", "Africa/Accra"),
        ("gst", "Asia/Dubai"),
        ("gyt", "America/Guyana"),
        ("hadt", "America/Adak"),
        ("hast", "America/Adak"),
        ("hdt", "Pacific/Honolulu"),
        ("hkst", "Asia/Hong_Kong"),
        ("hkt", "Asia/Hong_Kong"),
        ("hovst", "Asia/Hovd"),
        ("hovt", "Asia/Hovd"),
        ("hpt", "Pacific/Honolulu"),
        ("hst", "Pacific/Honolulu"),
        ("hwt", "Pacific/Honolulu"),
        ("ict", "Asia/Bangkok"),
        ("iddt", "Asia/Jerusalem"),
        ("idt", "Asia/Jerusalem"),
        ("ihst", "Asia/Colombo"),
        ("iot", "Indian/Chagos"),
        ("irdt", "Asia/Tehran"),
        ("irkst", "Asia/Irkutsk"),
        ("irkt", "Asia/Irkutsk"),
        ("irst", "Asia/Tehran"),
        ("isst", "Atlantic/Reykjavik"),
        ("ist", "Asia/Jerusalem"),
        ("javt", "Asia/Jakarta"),
        ("jdt", "Asia/Tokyo"),
        ("jst", "Asia/Tokyo"),
        ("kart", "Asia/Karachi"),
        ("kast", "Asia/Kashgar"),
        ("kdt", "Asia/Seoul"),
        ("kgst", "Asia/Bishkek"),
        ("kgt", "Asia/Bishkek"),
        ("kizst", "Asia/Qyzylorda"),
        ("kizt", "Asia/Qyzylorda"),
        ("kmt", "Europe/Vilnius"),
        ("kost", "Pacific/Kosrae"),
        ("krast", "Asia/Krasnoyarsk"),
        ("krat", "Asia/Krasnoyarsk"),
        ("kst", "Asia/Seoul"),
        ("kuyst", "Europe/Samara"),
        ("kuyt", "Europe/Samara"),
        ("kwat", "Kwajalein"),
        ("kwat", "Pacific/Kwajalein"),
        ("lhst", "Australia/Lord_Howe"),
        ("lint", "Pacific/Kiritimati"),
        ("lkt", "Asia/Colombo"),
        ("lont", "Asia/Chongqing"),
        ("lrt", "Africa/Monrovia"),
        ("lst", "Europe/Riga"),
        ("madmt", "Atlantic/Madeira"),
        ("madst", "Atlantic/Madeira"),
        ("madt", "Atlantic/Madeira"),
        ("magst", "Asia/Magadan"),
        ("magt", "Asia/Magadan"),
        ("malst", "Asia/Singapore"),
        ("malt", "Asia/Singapore"),
        ("mart", "Pacific/Marquesas"),
        ("mawt", "Antarctica/Mawson"),
        ("mddt", "America/Cambridge_Bay"),
        ("mdst", "Europe/Moscow"),
        ("mdt", "America/Denver"),
        ("mht", "Pacific/Kwajalein"),
        ("mmt", "Europe/Moscow"),
        ("most", "Asia/Macao"),
        ("mot", "Asia/Macao"),
        ("mpt", "America/Denver"),
        ("msd", "Europe/Moscow"),
        ("msk", "Europe/Moscow"),
        ("mst", "America/Denver"),
        ("mut", "Indian/Mauritius"),
        ("mvt", "Indian/Maldives"),
        ("mwt", "America/Denver"),
        ("myt", "Asia/Kuala_Lumpur"),
        ("ncst", "Pacific/Noumea"),
        ("nct", "Pacific/Noumea"),
        ("nddt", "America/St_Johns"),
        ("ndt", "America/St_Johns"),
        ("negt", "America/Paramaribo"),
        ("nest", "Europe/Amsterdam"),
        ("net", "Europe/Amsterdam"),
        ("nft", "Pacific/Norfolk"),
        ("novst", "Asia/Novosibirsk"),
        ("novt", "Asia/Novosibirsk"),
        ("npt", "America/St_Johns"),
        ("nrt", "Pacific/Nauru"),
        ("nst", "America/St_Johns"),
        ("nut", "Pacific/Niue"),
        ("nwt", "America/St_Johns"),
        ("nzdt", "Pacific/Auckland"),
        ("nzmt", "Pacific/Auckland"),
        ("nzst", "Pacific/Auckland"),
        ("omsst", "Asia/Omsk"),
        ("omst", "Asia/Omsk"),
        ("orast", "Asia/Oral"),
        ("orat", "Asia/Oral"),
        ("pddt", "America/Inuvik"),
        ("pdt", "America/Los_Angeles"),
        ("pest", "America/Lima"),
        ("petst", "Asia/Kamchatka"),
        ("pett", "Asia/Kamchatka"),
        ("pet", "America/Lima"),
        ("phot", "Pacific/Enderbury"),
        ("phst", "Asia/Manila"),
        ("pht", "Asia/Manila"),
        ("pkst", "Asia/Karachi"),
        ("pkt", "Asia/Karachi"),
        ("pmdt", "America/Miquelon"),
        ("pmst", "America/Miquelon"),
        ("pmt", "America/Paramaribo"),
        ("ppt", "America/Los_Angeles"),
        ("pst", "America/Los_Angeles"),
        ("pwt", "America/Los_Angeles"),
        ("pyst", "America/Asuncion"),
        ("pyt", "America/Asuncion"),
        ("qyzst", "Asia/Qyzylorda"),
        ("qyzt", "Asia/Qyzylorda"),
        ("ret", "Indian/Reunion"),
        ("rmt", "Europe/Riga"),
        ("rott", "Antarctica/Rothera"),
        ("sakst", "Asia/Sakhalin"),
        ("sakt", "Asia/Sakhalin"),
        ("samst", "Asia/Samarkand"),
        ("samt", "Asia/Samarkand"),
        ("sast", "Africa/Johannesburg"),
        ("sbt", "Pacific/Guadalcanal"),
        ("sct", "Indian/Mahe"),
        ("sgt", "Asia/Singapore"),
        ("shest", "Asia/Aqtau"),
        ("shet", "Asia/Aqtau"),
        ("slst", "Africa/Freetown"),
        ("smt", "Asia/Saigon"),
        ("srt", "America/Paramaribo"),
        ("sst", "Pacific/Samoa"),
        ("svest", "Asia/Yekaterinburg"),
        ("svet", "Asia/Yekaterinburg"),
        ("syot", "Antarctica/Syowa"),
        ("taht", "Pacific/Tahiti"),
        ("tasst", "Asia/Samarkand"),
        ("tast", "Asia/Samarkand"),
        ("tbist", "Asia/Tbilisi"),
        ("tbit", "Asia/Tbilisi"),
        ("tft", "Indian/Kerguelen"),
        ("tjt", "Asia/Dushanbe"),
        ("tlt", "Asia/Dili"),
        ("tlt", "Asia/Dili"),
        ("tmt", "Asia/Tehran"),
        ("tost", "Pacific/Tongatapu"),
        ("tot", "Pacific/Tongatapu"),
        ("trst", "Europe/Istanbul"),
        ("trt", "Europe/Istanbul"),
        ("ulast", "Asia/Ulaanbaatar"),
        ("ulat", "Asia/Ulaanbaatar"),
        ("urast", "Asia/Oral"),
        ("urat", "Asia/Oral"),
        ("urut", "Asia/Urumqi"),
        ("uyhst", "America/Montevideo"),
        ("uyst", "America/Montevideo"),
        ("uyt", "America/Montevideo"),
        ("uzst", "Asia/Samarkand"),
        ("uzt", "Asia/Samarkand"),
        ("vet", "America/Caracas"),
        ("vlasst", "Asia/Vladivostok"),
        ("vlast", "Asia/Vladivostok"),
        ("vlat", "Asia/Vladivostok"),
        ("vost", "Antarctica/Vostok"),
        ("vust", "Pacific/Efate"),
        ("vut", "Pacific/Efate"),
        ("warst", "America/Mendoza"),
        ("wart", "America/Mendoza"),
        ("wast", "Africa/Windhoek"),
        ("wat", "Africa/Dakar"),
        ("wemt", "Europe/Lisbon"),
        ("west", "Europe/Paris"),
        ("wet", "Europe/Paris"),
        ("wgst", "America/Godthab"),
        ("wgt", "America/Godthab"),
        ("wit", "Asia/Jakarta"),
        ("wst", "Australia/Perth"),
        ("yakst", "Asia/Yakutsk"),
        ("yakt", "Asia/Yakutsk"),
        ("yddt", "America/Dawson"),
        ("ydt", "America/Dawson"),
        ("yekst", "Asia/Yekaterinburg"),
        ("yekt", "Asia/Yekaterinburg"),
        ("yerst", "Asia/Yerevan"),
        ("yert", "Asia/Yerevan"),
        ("ypt", "America/Dawson"),
        ("yst", "America/Anchorage"),
        ("ywt", "America/Dawson"),
        ("zzz", "Antarctica/Davis"),
    ])
});

static PRIORITY_B_LIST: LazyLock<HashMap<&str, (bool, i32, &str)>> = LazyLock::new(|| {
    HashMap::from([
        ("acst", (true, -14400, "America/Porto_Acre")),
        ("act", (false, -18000, "America/Porto_Acre")),
        ("addt", (true, -7200, "America/Goose_Bay")),
        ("adt", (true, -10800, "America/Halifax")),
        ("aft", (false, 16200, "Asia/Kabul")),
        ("ahdt", (true, -32400, "America/Anchorage")),
        ("ahst", (false, -36000, "America/Anchorage")),
        ("akdt", (true, -28800, "America/Anchorage")),
        ("akst", (false, -32400, "America/Anchorage")),
        ("aktst", (true, 21600, "Asia/Aqtobe")),
        ("aktt", (false, 14400, "Asia/Aqtobe")),
        ("aktt", (false, 18000, "Asia/Aqtobe")),
        ("aktt", (false, 21600, "Asia/Aqtobe")),
        ("almst", (true, 25200, "Asia/Almaty")),
        ("almt", (false, 18000, "Asia/Almaty")),
        ("almt", (false, 21600, "Asia/Almaty")),
        ("amst", (true, -10800, "America/Manaus")),
        ("amst", (true, 14400, "Asia/Yerevan")),
        ("amst", (true, 18000, "Asia/Yerevan")),
        ("amt", (false, -14400, "America/Manaus")),
        ("amt", (false, 10800, "Asia/Yerevan")),
        ("amt", (false, 1172, "Europe/Amsterdam")),
        ("amt", (false, 14400, "Asia/Yerevan")),
        ("anast", (true, 43200, "Asia/Anadyr")),
        ("anast", (true, 46800, "Asia/Anadyr")),
        ("anast", (true, 50400, "Asia/Anadyr")),
        ("anat", (false, 39600, "Asia/Anadyr")),
        ("anat", (false, 43200, "Asia/Anadyr")),
        ("anat", (false, 46800, "Asia/Anadyr")),
        ("ant", (false, -16200, "America/Curacao")),
        ("apt", (true, -10800, "America/Halifax")),
        ("aqtst", (true, 18000, "Asia/Aqtau")),
        ("aqtst", (true, 21600, "Asia/Aqtau")),
        ("aqtt", (false, 14400, "Asia/Aqtau")),
        ("aqtt", (false, 18000, "Asia/Aqtau")),
        ("arst", (true, -7200, "America/Buenos_Aires")),
        ("art", (false, -10800, "America/Buenos_Aires")),
        ("ashst", (true, 18000, "Asia/Ashkhabad")),
        ("ashst", (true, 21600, "Asia/Ashkhabad")),
        ("asht", (false, 14400, "Asia/Ashkhabad")),
        ("asht", (false, 18000, "Asia/Ashkhabad")),
        ("ast", (false, -14400, "America/Curacao")),
        ("ast", (false, 10800, "Asia/Riyadh")),
        ("awt", (true, -10800, "America/Halifax")),
        ("azomt", (true, 0, "Atlantic/Azores")),
        ("azost", (true, 0, "Atlantic/Azores")),
        ("azot", (false, -3600, "Atlantic/Azores")),
        ("azst", (true, 14400, "Asia/Baku")),
        ("azst", (true, 18000, "Asia/Baku")),
        ("azt", (false, 10800, "Asia/Baku")),
        ("azt", (false, 14400, "Asia/Baku")),
        ("bakst", (true, 14400, "Asia/Baku")),
        ("bakst", (true, 18000, "Asia/Baku")),
        ("bakt", (false, 10800, "Asia/Baku")),
        ("bakt", (false, 14400, "Asia/Baku")),
        ("bdst", (true, 7200, "Europe/London")),
        ("bdt", (true, -36000, "America/Adak")),
        ("bdt", (false, 21600, "Asia/Dacca")),
        ("beat", (false, 9000, "Africa/Mogadishu")),
        ("beaut", (false, 9885, "Africa/Nairobi")),
        ("bmt", (false, -14308, "America/Barbados")),
        ("bmt", (false, -3996, "Africa/Banjul")),
        ("bmt", (false, 6264, "Europe/Tiraspol")),
        ("bnt", (false, 27000, "Asia/Brunei")),
        ("bnt", (false, 28800, "Asia/Brunei")),
        ("bortst", (true, 30000, "Asia/Kuching")),
        ("bort", (false, 27000, "Asia/Kuching")),
        ("bort", (false, 28800, "Asia/Kuching")),
        ("bost", (true, -12756, "America/La_Paz")),
        ("bot", (false, -14400, "America/La_Paz")),
        ("brst", (true, -7200, "America/Sao_Paulo")),
        ("brt", (false, -10800, "America/Sao_Paulo")),
        ("bst", (false, -39600, "America/Adak")),
        ("bst", (false, 3600, "Europe/London")),
        ("bst", (true, 3600, "Europe/London")),
        ("btt", (false, 21600, "Asia/Thimbu")),
        ("burt", (false, 23400, "Asia/Kolkata")),
        ("cant", (false, -3600, "Atlantic/Canary")),
        ("cast", (false, 34200, "Australia/Adelaide")),
        ("cat", (false, -36000, "America/Anchorage")),
        ("cat", (false, 7200, "Africa/Khartoum")),
        ("cawt", (true, -32400, "America/Anchorage")),
        ("cddt", (true, -14400, "America/Rankin_Inlet")),
        ("cdt", (true, -14400, "America/Havana")),
        ("cdt", (true, -18000, "America/Chicago")),
        ("cdt", (true, 32400, "Asia/Shanghai")),
        ("cemt", (true, 10800, "Europe/Berlin")),
        ("cest", (true, 10800, "Europe/Kaliningrad")),
        ("cest", (true, 7200, "Europe/Berlin")),
        ("cet", (false, 3600, "Europe/Berlin")),
        ("cet", (false, 7200, "Europe/Kaliningrad")),
        ("cgst", (true, -3600, "America/Scoresbysund")),
        ("cgt", (false, -7200, "America/Scoresbysund")),
        ("chadt", (true, 49500, "Pacific/Chatham")),
        ("chast", (false, 45900, "Pacific/Chatham")),
        ("chat", (false, 30600, "Asia/Harbin")),
        ("chat", (false, 32400, "Asia/Harbin")),
        ("chdt", (true, -19800, "America/Belize")),
        ("chost", (true, 36000, "Asia/Choibalsan")),
        ("chot", (false, 32400, "Asia/Choibalsan")),
        ("cit", (false, 28800, "Asia/Dili")),
        ("cjt", (false, 32400, "Asia/Sakhalin")),
        ("ckhst", (true, -34200, "Pacific/Rarotonga")),
        ("ckt", (false, -36000, "Pacific/Rarotonga")),
        ("clst", (true, -10800, "America/Santiago")),
        ("clt", (false, -14400, "America/Santiago")),
        ("cost", (true, -14400, "America/Bogota")),
        ("cot", (false, -18000, "America/Bogota")),
        ("cpt", (true, -18000, "America/Chicago")),
        ("cst", (false, -18000, "America/Havana")),
        ("cst", (false, -21600, "America/Chicago")),
        ("cst", (false, 28800, "Asia/Shanghai")),
        ("cst", (false, 34200, "Australia/Adelaide")),
        ("cst", (true, 37800, "Australia/Adelaide")),
        ("cvst", (true, -3600, "Atlantic/Cape_Verde")),
        ("cvt", (false, -3600, "Atlantic/Cape_Verde")),
        ("cvt", (false, -7200, "Atlantic/Cape_Verde")),
        ("cwt", (true, -18000, "America/Chicago")),
        ("chst", (false, 36000, "Pacific/Guam")),
        ("dact", (false, 21600, "Asia/Dacca")),
        ("davt", (false, 25200, "Antarctica/Davis")),
        ("ddut", (false, 36000, "Antarctica/DumontDUrville")),
        ("dusst", (true, 21600, "Asia/Dushanbe")),
        ("dusst", (true, 25200, "Asia/Dushanbe")),
        ("dust", (false, 18000, "Asia/Dushanbe")),
        ("dust", (false, 21600, "Asia/Dushanbe")),
        ("easst", (true, -18000, "Chile/EasterIsland")),
        ("easst", (true, -21600, "Chile/EasterIsland")),
        ("east", (false, -21600, "Chile/EasterIsland")),
        ("east", (false, -25200, "Chile/EasterIsland")),
        ("east", (true, 14400, "Indian/Antananarivo")),
        ("eat", (false, 10800, "Africa/Khartoum")),
        ("ect", (false, -18000, "America/Guayaquil")),
        ("eddt", (true, -10800, "America/Iqaluit")),
        ("edt", (true, -14400, "America/New_York")),
        ("eest", (true, 10800, "Europe/Helsinki")),
        ("eet", (false, 7200, "Europe/Helsinki")),
        ("egst", (true, 0, "America/Scoresbysund")),
        ("egt", (false, -3600, "America/Scoresbysund")),
        ("ehdt", (true, -16200, "America/Santo_Domingo")),
        ("eit", (false, 32400, "Asia/Jayapura")),
        ("ept", (true, -14400, "America/New_York")),
        ("est", (false, -18000, "America/New_York")),
        ("est", (false, 36000, "Australia/Melbourne")),
        ("est", (true, 39600, "Australia/Melbourne")),
        ("ewt", (true, -14400, "America/New_York")),
        ("fjst", (true, 46800, "Pacific/Fiji")),
        ("fjt", (false, 43200, "Pacific/Fiji")),
        ("fkst", (true, -10800, "Atlantic/Stanley")),
        ("fkst", (true, -7200, "Atlantic/Stanley")),
        ("fkt", (false, -10800, "Atlantic/Stanley")),
        ("fkt", (false, -14400, "Atlantic/Stanley")),
        ("fnst", (true, -3600, "America/Noronha")),
        ("fnt", (false, -7200, "America/Noronha")),
        ("fort", (false, 14400, "Asia/Aqtau")),
        ("fort", (false, 18000, "Asia/Aqtau")),
        ("frust", (true, 21600, "Asia/Bishkek")),
        ("frust", (true, 25200, "Asia/Bishkek")),
        ("frut", (false, 18000, "Asia/Bishkek")),
        ("frut", (false, 21600, "Asia/Bishkek")),
        ("galt", (false, -21600, "Pacific/Galapagos")),
        ("gamt", (false, -32400, "Pacific/Gambier")),
        ("gbgt", (false, -13500, "America/Guyana")),
        ("gest", (true, 14400, "Asia/Tbilisi")),
        ("get", (false, 10800, "Asia/Tbilisi")),
        ("get", (false, 14400, "Asia/Tbilisi")),
        ("gft", (false, -10800, "America/Cayenne")),
        ("gft", (false, -14400, "America/Cayenne")),
        ("ghst", (true, 1200, "Africa/Accra")),
        ("gst", (false, 14400, "Asia/Dubai")),
        ("gyt", (false, -14400, "America/Guyana")),
        ("hadt", (true, -32400, "America/Adak")),
        ("hast", (false, -36000, "America/Adak")),
        ("hdt", (true, -34200, "Pacific/Honolulu")),
        ("hkst", (true, 32400, "Asia/Hong_Kong")),
        ("hkt", (false, 28800, "Asia/Hong_Kong")),
        ("hovst", (true, 28800, "Asia/Hovd")),
        ("hovt", (false, 21600, "Asia/Hovd")),
        ("hovt", (false, 25200, "Asia/Hovd")),
        ("hpt", (true, -34200, "Pacific/Honolulu")),
        ("hst", (false, -36000, "Pacific/Honolulu")),
        ("hwt", (true, -34200, "Pacific/Honolulu")),
        ("ict", (false, 25200, "Asia/Bangkok")),
        ("iddt", (true, 14400, "Asia/Jerusalem")),
        ("idt", (true, 10800, "Asia/Jerusalem")),
        ("ihst", (true, 21600, "Asia/Colombo")),
        ("iot", (false, 18000, "Indian/Chagos")),
        ("iot", (false, 21600, "Indian/Chagos")),
        ("irdt", (true, 16200, "Asia/Tehran")),
        ("irkst", (true, 28800, "Asia/Irkutsk")),
        ("irkst", (true, 32400, "Asia/Irkutsk")),
        ("irkt", (false, 25200, "Asia/Irkutsk")),
        ("irkt", (false, 28800, "Asia/Irkutsk")),
        ("irst", (false, 12600, "Asia/Tehran")),
        ("isst", (true, 0, "Atlantic/Reykjavik")),
        ("ist", (false, -3600, "Atlantic/Reykjavik")),
        ("ist", (false, 19800, "Asia/Kolkata")),
        ("ist", (true, 2079, "Europe/Dublin")),
        ("ist", (true, 23400, "Asia/Kolkata")),
        ("ist", (false, 3600, "Europe/Dublin")),
        ("ist", (true, 3600, "Europe/Dublin")),
        ("ist", (false, 7200, "Asia/Jerusalem")),
        ("javt", (false, 26400, "Asia/Jakarta")),
        ("jdt", (true, 36000, "Asia/Tokyo")),
        ("jst", (false, 32400, "Asia/Tokyo")),
        ("kart", (false, 18000, "Asia/Karachi")),
        ("kast", (false, 18000, "Asia/Kashgar")),
        ("kast", (false, 19800, "Asia/Kashgar")),
        ("kdt", (true, 36000, "Asia/Seoul")),
        ("kgst", (true, 21600, "Asia/Bishkek")),
        ("kgt", (false, 18000, "Asia/Bishkek")),
        ("kizst", (true, 21600, "Asia/Qyzylorda")),
        ("kizt", (false, 14400, "Asia/Qyzylorda")),
        ("kizt", (false, 18000, "Asia/Qyzylorda")),
        ("kizt", (false, 21600, "Asia/Qyzylorda")),
        ("kmt", (false, 5736, "Europe/Vilnius")),
        ("kost", (false, 39600, "Pacific/Kosrae")),
        ("kost", (false, 43200, "Pacific/Kosrae")),
        ("krast", (true, 25200, "Asia/Krasnoyarsk")),
        ("krast", (true, 28800, "Asia/Krasnoyarsk")),
        ("krat", (false, 21600, "Asia/Krasnoyarsk")),
        ("krat", (false, 25200, "Asia/Krasnoyarsk")),
        ("kst", (false, 32400, "Asia/Seoul")),
        ("kst", (false, 30600, "Asia/Pyongyang")),
        ("kst", (false, 32400, "Asia/Pyongyang")),
        ("kuyst", (true, 10800, "Europe/Samara")),
        ("kuyst", (true, 14400, "Europe/Samara")),
        ("kuyst", (true, 18000, "Europe/Samara")),
        ("kuyt", (false, 10800, "Europe/Samara")),
        ("kuyt", (false, 14400, "Europe/Samara")),
        ("kwat", (false, -43200, "Kwajalein")),
        ("kwat", (false, -43200, "Pacific/Kwajalein")),
        ("lhst", (false, 37800, "Australia/Lord_Howe")),
        ("lhst", (true, 39600, "Australia/Lord_Howe")),
        ("lhst", (true, 41400, "Australia/Lord_Howe")),
        ("lint", (false, -36000, "Pacific/Kiritimati")),
        ("lint", (false, 50400, "Pacific/Kiritimati")),
        ("lkt", (false, 21600, "Asia/Colombo")),
        ("lkt", (false, 23400, "Asia/Colombo")),
        ("lont", (false, 25200, "Asia/Chongqing")),
        ("lrt", (false, -2670, "Africa/Monrovia")),
        ("lst", (true, 9384, "Europe/Riga")),
        ("madmt", (true, 3600, "Atlantic/Madeira")),
        ("madst", (true, 0, "Atlantic/Madeira")),
        ("madt", (false, -3600, "Atlantic/Madeira")),
        ("magst", (true, 43200, "Asia/Magadan")),
        ("magt", (false, 36000, "Asia/Magadan")),
        ("malst", (true, 26400, "Asia/Singapore")),
        ("malt", (false, 25200, "Asia/Singapore")),
        ("malt", (false, 26400, "Asia/Singapore")),
        ("malt", (false, 27000, "Asia/Singapore")),
        ("mart", (false, -34200, "Pacific/Marquesas")),
        ("mawt", (false, 21600, "Antarctica/Mawson")),
        ("mddt", (true, -18000, "America/Cambridge_Bay")),
        ("mdst", (true, 16248, "Europe/Moscow")),
        ("mdt", (true, -21600, "America/Denver")),
        ("mht", (false, 43200, "Pacific/Kwajalein")),
        ("mmt", (false, 28656, "Asia/Makassar")),
        ("mmt", (false, 9048, "Europe/Moscow")),
        ("most", (true, 32400, "Asia/Macao")),
        ("mot", (false, 28800, "Asia/Macao")),
        ("mpt", (true, -21600, "America/Denver")),
        ("mpt", (false, 36000, "Pacific/Saipan")),
        ("msd", (true, 14400, "Europe/Moscow")),
        ("msk", (false, 10800, "Europe/Moscow")),
        ("mst", (false, -25200, "America/Denver")),
        ("mst", (true, 12648, "Europe/Moscow")),
        ("mut", (false, 14400, "Indian/Mauritius")),
        ("mvt", (false, 18000, "Indian/Maldives")),
        ("mwt", (true, -21600, "America/Denver")),
        ("myt", (false, 28800, "Asia/Kuala_Lumpur")),
        ("ncst", (true, 43200, "Pacific/Noumea")),
        ("nct", (false, 39600, "Pacific/Noumea")),
        ("nddt", (true, -5400, "America/St_Johns")),
        ("ndt", (true, -36000, "Pacific/Midway")),
        ("ndt", (true, -9000, "America/St_Johns")),
        ("ndt", (true, -9052, "America/St_Johns")),
        ("negt", (false, -12600, "America/Paramaribo")),
        ("nest", (true, 4800, "Europe/Amsterdam")),
        ("net", (false, 1200, "Europe/Amsterdam")),
        ("nft", (false, 41400, "Pacific/Norfolk")),
        ("novst", (true, 25200, "Asia/Novosibirsk")),
        ("novt", (false, 21600, "Asia/Novosibirsk")),
        ("npt", (true, -36000, "America/Adak")),
        ("npt", (true, -9000, "America/St_Johns")),
        ("npt", (false, 20700, "Asia/Katmandu")),
        ("nrt", (false, 41400, "Pacific/Nauru")),
        ("nrt", (false, 43200, "Pacific/Nauru")),
        ("nst", (false, -12600, "America/St_Johns")),
        ("nst", (false, -12652, "America/St_Johns")),
        ("nst", (false, -39600, "America/Adak")),
        ("nst", (true, 4772, "Europe/Amsterdam")),
        ("nut", (false, -39600, "Pacific/Niue")),
        ("nwt", (true, -9000, "America/St_Johns")),
        ("nzdt", (true, 46800, "Pacific/Auckland")),
        ("nzmt", (false, 41400, "Pacific/Auckland")),
        ("nzst", (false, 43200, "Pacific/Auckland")),
        ("omsst", (true, 21600, "Asia/Omsk")),
        ("omsst", (true, 25200, "Asia/Omsk")),
        ("omst", (false, 18000, "Asia/Omsk")),
        ("omst", (false, 21600, "Asia/Omsk")),
        ("orast", (true, 18000, "Asia/Oral")),
        ("orat", (false, 14400, "Asia/Oral")),
        ("orat", (false, 18000, "Asia/Oral")),
        ("pddt", (true, -21600, "America/Inuvik")),
        ("pdt", (true, -25200, "America/Los_Angeles")),
        ("pest", (true, -14400, "America/Lima")),
        ("petst", (true, 43200, "Asia/Kamchatka")),
        ("petst", (true, 46800, "Asia/Kamchatka")),
        ("pett", (false, 39600, "Asia/Kamchatka")),
        ("pett", (false, 43200, "Asia/Kamchatka")),
        ("pet", (false, -18000, "America/Lima")),
        ("phot", (false, -39600, "Pacific/Enderbury")),
        ("phot", (false, 46800, "Pacific/Enderbury")),
        ("phst", (true, 32400, "Asia/Manila")),
        ("pht", (false, 28800, "Asia/Manila")),
        ("pkst", (true, 21600, "Asia/Karachi")),
        ("pkt", (false, 18000, "Asia/Karachi")),
        ("pmdt", (true, -7200, "America/Miquelon")),
        ("pmst", (false, -10800, "America/Miquelon")),
        ("pmt", (false, -13236, "America/Paramaribo")),
        ("pmt", (false, -13252, "America/Paramaribo")),
        ("pmt", (false, 26240, "Asia/Pontianak")),
        ("pmt", (false, 36000, "Antarctica/DumontDUrville")),
        ("ppt", (true, -25200, "America/Los_Angeles")),
        ("pst", (false, -28800, "America/Los_Angeles")),
        ("pwt", (true, -25200, "America/Los_Angeles")),
        ("pyst", (true, -10800, "America/Asuncion")),
        ("pyt", (false, -10800, "America/Asuncion")),
        ("pyt", (false, -14400, "America/Asuncion")),
        ("qyzst", (true, 25200, "Asia/Qyzylorda")),
        ("qyzt", (false, 18000, "Asia/Qyzylorda")),
        ("qyzt", (false, 21600, "Asia/Qyzylorda")),
        ("ret", (false, 14400, "Indian/Reunion")),
        ("rmt", (false, 5784, "Europe/Riga")),
        ("rott", (false, -10800, "Antarctica/Rothera")),
        ("sakst", (true, 39600, "Asia/Sakhalin")),
        ("sakt", (false, 36000, "Asia/Sakhalin")),
        ("samst", (true, 18000, "Europe/Samara")),
        ("samst", (true, 21600, "Asia/Samarkand")),
        ("samt", (false, -41400, "Pacific/Samoa")),
        ("samt", (false, 14400, "Asia/Samarkand")),
        ("samt", (false, 18000, "Asia/Samarkand")),
        ("sast", (true, 10800, "Africa/Johannesburg")),
        ("sast", (false, 7200, "Africa/Johannesburg")),
        ("sbt", (false, 39600, "Pacific/Guadalcanal")),
        ("sct", (false, 14400, "Indian/Mahe")),
        ("sgt", (false, 28800, "Asia/Singapore")),
        ("shest", (true, 21600, "Asia/Aqtau")),
        ("shet", (false, 18000, "Asia/Aqtau")),
        ("shet", (false, 21600, "Asia/Aqtau")),
        ("slst", (true, -1200, "Africa/Freetown")),
        ("slst", (true, 3600, "Africa/Freetown")),
        ("smt", (false, 25580, "Asia/Saigon")),
        ("srt", (false, -10800, "America/Paramaribo")),
        ("sst", (false, -39600, "Pacific/Samoa")),
        ("svest", (true, 18000, "Asia/Yekaterinburg")),
        ("svest", (true, 21600, "Asia/Yekaterinburg")),
        ("svet", (false, 14400, "Asia/Yekaterinburg")),
        ("svet", (false, 18000, "Asia/Yekaterinburg")),
        ("syot", (false, 10800, "Antarctica/Syowa")),
        ("taht", (false, -36000, "Pacific/Tahiti")),
        ("tasst", (true, 21600, "Asia/Samarkand")),
        ("tasst", (true, 25200, "Asia/Samarkand")),
        ("tast", (false, 18000, "Asia/Tashkent")),
        ("tast", (false, 21600, "Asia/Samarkand")),
        ("tbist", (true, 14400, "Asia/Tbilisi")),
        ("tbist", (true, 18000, "Asia/Tbilisi")),
        ("tbit", (false, 10800, "Asia/Tbilisi")),
        ("tbit", (false, 14400, "Asia/Tbilisi")),
        ("tft", (false, 18000, "Indian/Kerguelen")),
        ("tjt", (false, 18000, "Asia/Dushanbe")),
        ("tlt", (false, 28800, "Asia/Dili")),
        ("tlt", (false, 32400, "Asia/Dili")),
        ("tmt", (false, 12344, "Asia/Tehran")),
        ("tmt", (false, 14400, "Asia/Ashgabat")),
        ("tmt", (false, 18000, "Asia/Ashgabat")),
        ("tmt", (false, 5940, "Europe/Tallinn")),
        ("tost", (true, 50400, "Pacific/Tongatapu")),
        ("tot", (false, 46800, "Pacific/Tongatapu")),
        ("trst", (true, 14400, "Europe/Istanbul")),
        ("trt", (false, 10800, "Europe/Istanbul")),
        ("ulast", (true, 32400, "Asia/Ulaanbaatar")),
        ("ulat", (false, 25200, "Asia/Ulaanbaatar")),
        ("ulat", (false, 28800, "Asia/Ulaanbaatar")),
        ("urast", (true, 18000, "Asia/Oral")),
        ("urast", (true, 21600, "Asia/Oral")),
        ("urat", (false, 14400, "Asia/Oral")),
        ("urat", (false, 18000, "Asia/Oral")),
        ("urat", (false, 21600, "Asia/Oral")),
        ("urut", (false, 21600, "Asia/Urumqi")),
        ("uyhst", (true, -10800, "America/Montevideo")),
        ("uyhst", (true, -9000, "America/Montevideo")),
        ("uyst", (true, -7200, "America/Montevideo")),
        ("uyt", (false, -10800, "America/Montevideo")),
        ("uzst", (true, 21600, "Asia/Samarkand")),
        ("uzt", (false, 18000, "Asia/Samarkand")),
        ("vet", (false, -14400, "America/Caracas")),
        ("vet", (false, -16200, "America/Caracas")),
        ("vlasst", (true, 36000, "Asia/Vladivostok")),
        ("vlast", (true, 39600, "Asia/Vladivostok")),
        ("vlat", (false, 36000, "Asia/Vladivostok")),
        ("vost", (false, 21600, "Antarctica/Vostok")),
        ("vust", (true, 43200, "Pacific/Efate")),
        ("vut", (false, 39600, "Pacific/Efate")),
        ("warst", (true, -10800, "America/Mendoza")),
        ("wart", (false, -14400, "America/Mendoza")),
        ("wast", (true, 7200, "Africa/Windhoek")),
        ("wat", (false, -3600, "Africa/Dakar")),
        ("wat", (false, 0, "Africa/Freetown")),
        ("wat", (false, 3600, "Africa/Brazzaville")),
        ("wemt", (true, 7200, "Europe/Lisbon")),
        ("west", (true, 3600, "Europe/Paris")),
        ("west", (true, 7200, "Europe/Luxembourg")),
        ("wet", (false, 0, "Europe/Paris")),
        ("wet", (false, 3600, "Europe/Luxembourg")),
        ("wgst", (true, -7200, "America/Godthab")),
        ("wgt", (false, -10800, "America/Godthab")),
        ("wit", (false, 25200, "Asia/Jakarta")),
        ("wit", (false, 27000, "Asia/Jakarta")),
        ("wit", (false, 28800, "Asia/Jakarta")),
        ("wst", (false, -39600, "Pacific/Apia")),
        ("wst", (false, 28800, "Australia/Perth")),
        ("wst", (true, 32400, "Australia/Perth")),
        ("yakst", (true, 32400, "Asia/Yakutsk")),
        ("yakst", (true, 36000, "Asia/Yakutsk")),
        ("yakt", (false, 28800, "Asia/Yakutsk")),
        ("yakt", (false, 32400, "Asia/Yakutsk")),
        ("yddt", (true, -25200, "America/Dawson")),
        ("ydt", (true, -28800, "America/Dawson")),
        ("yekst", (true, 21600, "Asia/Yekaterinburg")),
        ("yekt", (false, 18000, "Asia/Yekaterinburg")),
        ("yerst", (true, 14400, "Asia/Yerevan")),
        ("yerst", (true, 18000, "Asia/Yerevan")),
        ("yert", (false, 10800, "Asia/Yerevan")),
        ("yert", (false, 14400, "Asia/Yerevan")),
        ("ypt", (true, -28800, "America/Dawson")),
        ("yst", (false, -32400, "America/Anchorage")),
        ("ywt", (true, -28800, "America/Dawson")),
        ("zzz", (false, 0, "Antarctica/Davis")),
    ])
});
