[package]
name = "libwikitext-parse-gpl"
description = "A Wikitext to AST parser (GPL parts)"
edition.workspace = true
license = "GPL-2.0-or-later"
version.workspace = true

[lints]
workspace = true

[dependencies]
either.workspace = true
html-escape.workspace = true
libwikitext-common.workspace = true
libwikitext-parse.workspace = true
peg.workspace = true
phf.workspace = true
regex.workspace = true

[dev-dependencies]
goldenfile.workspace = true
libwikitext-data.workspace = true
