[package]
name = "wiki-rs"
default-run = "wiki-rs"
description = "A high-performance offline reader of multistream MediaWiki dumps"
edition.workspace = true
license.workspace = true
# year.month.release-in-month
version = "2026.4.2-pre"

[dependencies]
axum = "0.8"
barely-css.workspace = true
bzip2-rs = "0.1"
env_logger.workspace = true
html-escape.workspace = true
indexmap.workspace = true
libphp-rs.workspace = true
libwikitext-common.workspace = true
libwikitext-data.workspace = true
libwikitext-lua-gpl.workspace = true
libwikitext-parse.workspace = true
libwikitext-parse-gpl.workspace = true
libwikitext-render.workspace = true
log.workspace = true
memmap2 = "0.9"
minidom.workspace = true
parking_lot = "0.12"
phf.workspace = true
piccolo.workspace = true
pico-args = "0.5"
prettyplease = { version = "0.2", optional = true }
proc-macro2 = { version = "1", optional = true }
quote = { version = "1", optional = true }
r2d2 = "0.8"
rayon.workspace = true
regex.workspace = true
sailfish = "0.10"
schnellru.workspace = true
serde.workspace = true
serde_json.workspace = true
syn = { version = "2", optional = true, features = ["parsing", "printing"] }
syntect.workspace = true
thiserror.workspace = true
time.workspace = true
tokio = { version = "1.47", features = ["macros", "net", "rt-multi-thread"] }
unicase = "2.8.1"
ureq = { version = "3.1", optional = true }

[features]
default = ["debug-styles"]
debug-styles = []
fetch-config = ["dep:prettyplease", "dep:proc-macro2", "dep:quote", "dep:syn", "dep:ureq"]

[lints]
workspace = true

[[bin]]
name = "fetch-config"
required-features = ["fetch-config"]
