[package]
name = "wiki-rs"
default-run = "wiki-rs"
description = "A high-performance offline reader of multistream MediaWiki dumps"
edition.workspace = true
license.workspace = true
# year.month.release-in-month
version = "2026.7.1"

[dependencies]
axum = "0.8"
barely-css.workspace = true
bzip2-rs = "0.1"
env_logger.workspace = true
html-escape.workspace = true
indexmap.workspace = true
libphp-rs.workspace = true
libwikitext-common.workspace = true
libwikitext-data.workspace = true
libwikitext-lua-gpl.workspace = true
libwikitext-parse.workspace = true
libwikitext-render.workspace = true
log.workspace = true
memmap2 = "0.9"
minidom.workspace = true
parking_lot = "0.12"
phf.workspace = true
piccolo.workspace = true
pico-args.workspace = true
r2d2 = "0.8"
rayon.workspace = true
regex.workspace = true
sailfish = "0.11"
schnellru.workspace = true
serde.workspace = true
serde_json.workspace = true
syntect.workspace = true
thiserror.workspace = true
time.workspace = true
tokio = { version = "1.47", features = ["macros", "net", "rt-multi-thread"] }
unicase = "2.8.1"

[features]
default = ["debug-styles"]
debug-styles = []

[lints]
workspace = true
