use libwikitext_common::{
    config::{Configuration, ConfigurationSource, MagicLinks},
    title::{Namespace, NamespaceCase::FirstLetter},
};
use std::sync::LazyLock;

pub(super) static CONFIG_SOURCE: ConfigurationSource = ConfigurationSource {
    annotation_tags: phf::phf_set! { "dummyanno", "ann2" },
    annotations_enabled: true,
    behavior_switch_words: phf::phf_map! {
        "__forcetoc__" => "forcetoc",
        "__hiddencat__" => "hiddencat",
        "__index__" => "index",
        "__newsectionlink__" => "newsectionlink",
        "__nocontentconvert__" => "nocontentconvert",
        "__noeditsection__" => "noeditsection",
        "__nogallery__" => "nogallery",
        "__noindex__" => "noindex",
        "__nonewsectionlink__" => "nonewsectionlink",
        "__notitleconvert__" => "notitleconvert",
        "__notoc__" => "notoc",
        "__toc__" => "toc"
    },
    // TODO: Sometimes <html>, sometimes <style>
    extension_tags: phf::phf_set! {
        "asidetag", "divtag", "embedtag", "gallery", "i18nattr", "i18ntag",
        "indicator", "inputbox", "langconvert", "nowiki", "pwraptest", "ref",
        "references", "sealtag", "section", "spantag", "statictag", "tag", "tåg"
    },
    function_hooks: phf::phf_map! {
        "anchorencode" => "anchorencode",
        "basepagename" => "basepagename",
        "basepagenamee" => "basepagenamee",
        "bcp47" => "bcp47",
        "contentmodel" => "contentmodel",
        "defaultsort" => "defaultsort",
        "dir" => "dir",
        "displaytitle" => "displaytitle",
        "filepath" => "filepath",
        "formatdate" => "formatdate",
        "formatnum" => "formatnum",
        "fullpagename" => "fullpagename",
        "fullpagenamee" => "fullpagenamee",
        "fullurl" => "fullurl",
        "fullurle" => "fullurle",
        "grammar" => "grammar",
        "if" => "if",
        "int" => "int",
        "interlanguagelink" => "interlanguagelink",
        "interwikilink" => "interwikilink",
        "language" => "language",
        "lc" => "lc",
        "lcfirst" => "lcfirst",
        "localurl" => "localurl",
        "localurle" => "localurle",
        "namespace" => "namespace",
        "namespacee" => "namespacee",
        "namespacenumber" => "namespacenumber",
        "ns" => "ns",
        "nse" => "nse",
        "numberofadmins" => "numberofadmins",
        "numberofarticles" => "numberofarticles",
        "numberoffiles" => "numberoffiles",
        "numberofpages" => "numberofpages",
        "numberofusers" => "numberofusers",
        "padleft" => "padleft",
        "padright" => "padright",
        "pageid" => "pageid",
        "pagename" => "pagename",
        "pagenamee" => "pagenamee",
        "pagesincategory" => "pagesincategory",
        "pagesize" => "pagesize",
        "revisionday" => "revisionday",
        "revisionday2" => "revisionday2",
        "revisionid" => "revisionid",
        "revisionmonth" => "revisionmonth",
        "revisionmonth1" => "revisionmonth1",
        "revisiontimestamp" => "revisiontimestamp",
        "revisionuser" => "revisionuser",
        "revisionyear" => "revisionyear",
        "rootpagename" => "rootpagename",
        "rootpagenamee" => "rootpagenamee",
        "special" => "special",
        "speciale" => "speciale",
        "subjectpagename" => "subjectpagename",
        "subjectpagenamee" => "subjectpagenamee",
        "subjectspace" => "subjectspace",
        "subjectspacee" => "subjectspacee",
        "subpagename" => "subpagename",
        "subpagenamee" => "subpagenamee",
        "tag" => "tag",
        "talkpagename" => "talkpagename",
        "talkpagenamee" => "talkpagenamee",
        "talkspace" => "talkspace",
        "talkspacee" => "talkspacee",
        "uc" => "uc",
        "ucfirst" => "ucfirst",
        "urlencode" => "urlencode",
    },
    interwiki_map: phf::phf_map! {
        "wikinvest" => "https://meta.wikimedia.org/wiki/Interwiki_map/discontinued#Wikinvest",
        "local" => "http://example.org/wiki/$1",
        // Local interwiki that matches a namespace name (T228616)
        "project" => "http://example.org/wiki/$1",
        "wikipedia" => "http://en.wikipedia.org/wiki/$1",
        // this has been updated in the live wikis, but the parser tests
        // expect the old value (as set in parserTest.inc:setupInterwikis())
        "meatball" => "http://www.usemod.com/cgi-bin/mb.pl?$1",
        "memoryalpha" => "http://www.memory-alpha.org/en/index.php/$1",
        "zh" => "http://zh.wikipedia.org/wiki/$1",
        "es" => "http://es.wikipedia.org/wiki/$1",
        "fr" => "http://fr.wikipedia.org/wiki/$1",
        "ru" => "http://ru.wikipedia.org/wiki/$1",
        "mi" => "http://example.org/wiki/$1",
        "mul" => "http://wikisource.org/wiki/$1",
        // added to core's ParserTestRunner::appendInterwikiSetup() to support
        // Parsoid tests [T254181]
        "en" => "http://en.wikipedia.org/wiki/$1",
        "stats" => "https://stats.wikimedia.org/$1",
        "gerrit" => "https://gerrit.wikimedia.org/$1",
    },
    language: "en",
    language_conversion_enabled: true,
    link_trail: "/^([a-z]+)(.*)$/",
    magic_links: MagicLinks {
        isbn: true,
        pmid: true,
        rfc: true,
    },
    namespaces: &[
        Namespace {
            id: -2,
            name: "Media",
            canonical: Some("Media"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: false,
            aliases: &[],
        },
        Namespace {
            id: -1,
            name: "Special",
            canonical: Some("Special"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: false,
            aliases: &[],
        },
        Namespace {
            id: 0,
            name: "",
            canonical: None,
            case: FirstLetter,
            content: true,
            default_content_model: None,
            subpages: false,
            aliases: &[],
        },
        Namespace {
            id: 1,
            name: "Talk",
            canonical: Some("Talk"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &[],
        },
        Namespace {
            id: 2,
            name: "User",
            canonical: Some("User"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &[],
        },
        Namespace {
            id: 3,
            name: "User talk",
            canonical: Some("User talk"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &[],
        },
        Namespace {
            id: 4,
            name: "Wikipedia",
            canonical: Some("Project"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &["WP"],
        },
        Namespace {
            id: 5,
            name: "Wikipedia talk",
            canonical: Some("Project talk"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &["WT"],
        },
        Namespace {
            id: 6,
            name: "File",
            canonical: Some("File"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: false,
            aliases: &["Image"],
        },
        Namespace {
            id: 7,
            name: "File talk",
            canonical: Some("File talk"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &["Image talk"],
        },
        Namespace {
            id: 10,
            name: "Template",
            canonical: Some("Template"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &["TM"],
        },
        Namespace {
            id: 11,
            name: "Template talk",
            canonical: Some("Template talk"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &[],
        },
        Namespace {
            id: 12,
            name: "Help",
            canonical: Some("Help"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &[],
        },
        Namespace {
            id: 14,
            name: "Category",
            canonical: Some("Category"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &[],
        },
        Namespace {
            id: 15,
            name: "Category talk",
            canonical: Some("Category talk"),
            case: FirstLetter,
            content: false,
            default_content_model: None,
            subpages: true,
            aliases: &[],
        },
    ],
    protocols: phf::phf_set! {
        "//", "ftp://", "gopher://", "http://", "https://", "irc://", "ircs://",
        "mailto:", "news:"
    },
    redirect_magic_words: phf::phf_set! {
        "#redirect"
    },
    valid_title_bytes: " %!\"$&'()*,\\-.\\/0-9:;=?@A-Z\\\\^_`a-z~\\x80-\\xFF+",
    variables: phf::phf_map! {
        "!" => "!",
        "=" => "=",
        "basepagename" => "basepagename",
        "basepagenamee" => "basepagenamee",
        "#bcp47" => "bcp47",
        "contentlanguage" => "contentlanguage",
        "#contentmodel" => "contentmodel",
        "currentday" => "currentday",
        "currentday2" => "currentday2",
        "currentdayname" => "currentdayname",
        "currentdow" => "currentdow",
        "currenthour" => "currenthour",
        "currentmonth" => "currentmonth",
        "currentmonth1" => "currentmonth1",
        "currentmonthabbrev" => "currentmonthabbrev",
        "currentmonthname" => "currentmonthname",
        "currentmonthnamegen" => "currentmonthnamegen",
        "currenttime" => "currenttime",
        "currenttimestamp" => "currenttimestamp",
        "currentversion" => "currentversion",
        "currentweek" => "currentweek",
        "currentyear" => "currentyear",
        "#dir" => "dir",
        "directionmark" => "directionmark",
        "fullpagename" => "fullpagename",
        "fullpagenamee" => "fullpagenamee",
        "#language" => "language",
        "localday" => "localday",
        "localday2" => "localday2",
        "localdayname" => "localdayname",
        "localdow" => "localdow",
        "localhour" => "localhour",
        "localmonth" => "localmonth",
        "localmonth2" => "localmonth",
        "localmonth1" => "localmonth1",
        "localmonthabbrev" => "localmonthabbrev",
        "localmonthname" => "localmonthname",
        "localmonthnamegen" => "localmonthnamegen",
        "localtime" => "localtime",
        "localtimestamp" => "localtimestamp",
        "localweek" => "localweek",
        "localyear" => "localyear",
        "namespace" => "namespace",
        "namespacee" => "namespacee",
        "namespacenumber" => "namespacenumber",
        "numberofadmins" => "numberofadmins",
        "numberofarticles" => "numberofarticles",
        "numberoffiles" => "numberoffiles",
        "numberofpages" => "numberofpages",
        "numberofusers" => "numberofusers",
        "pageid" => "pageid",
        "pagelanguage" => "pagelanguage",
        "pagename" => "pagename",
        "pagenamee" => "pagenamee",
        "revisionday" => "revisionday",
        "revisionday2" => "revisionday2",
        "revisionid" => "revisionid",
        "revisionmonth" => "revisionmonth",
        "revisionmonth1" => "revisionmonth1",
        "revisionsize" => "revisionsize",
        "revisiontimestamp" => "revisiontimestamp",
        "revisionuser" => "revisionuser",
        "revisionyear" => "revisionyear",
        "rootpagename" => "rootpagename",
        "rootpagenamee" => "rootpagenamee",
        "scriptpath" => "scriptpath",
        "server" => "server",
        "servername" => "servername",
        "sitename" => "sitename",
        "stylepath" => "stylepath",
        "subjectpagename" => "subjectpagename",
        "subjectpagenamee" => "subjectpagenamee",
        "subjectspace" => "subjectspace",
        "subjectspacee" => "subjectspacee",
        "subpagename" => "subpagename",
        "subpagenamee" => "subpagenamee",
        "talkpagename" => "talkpagename",
        "talkpagenamee" => "talkpagenamee",
        "talkspace" => "talkspace",
        "talkspacee" => "talkspacee",
        "userlanguage" => "userlanguage",
    },
};

pub(super) static CONFIG: LazyLock<Configuration> =
    LazyLock::new(|| Configuration::new(&CONFIG_SOURCE));
